### ISSUE TITLE
MonstersInTheCloset should now work

### ISSUE THREAD

**Issue by Minenash** [frank89722/BetterSafeBed#1]
Within the last week I released [v1.0.1](https://github.com/Minenash/MonstersInTheCloset/releases/tag/v1.0.1%2B1.16) of MonstersInTheCloset that actually removes the redundant check. I would've changed it earlier if I knew if was causing incompatibility. I found out about your mod through [this issue](https://github.com/Minenash/MonstersInTheCloset/issues/2) I got today.

**Comment by frank89722** [comment]
Fixed in CF description page
